from tkinter import *
from tkinter import messagebox
import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",password="root",database="CSCtutorial")
top= Tk()
top.geometry("500x500")
top.title('Registration form')
l=Label(top,text="Registration form", width=20,font=("Algerian",24)).place(x=45,y=40)
t1=StringVar()
t2=StringVar()
t3=StringVar()
t4=IntVar()
l =Label(top,text="FullName", width=20,font=("bold",12)).place(x=60,y=110)
e1=Entry(top,textvariable=t1).place(x=240,y=110)
l =Label(top,text="Email", width=20,font=("bold",12)).place(x=65,y=160)
e2=Entry(top,textvariable=t2).place(x=240,y=160)
var=IntVar()
l=Label(top,text="Country",width=20,font=("bold",12)).place(x=70,y=210)
listofcountry=[ 'India', 'America','Srilanka','Australia','Germany','Canada','China','Bangladesh','Malaysia','Italy','Londan','Pakisthan' ]
c=StringVar()
droplist=OptionMenu(top,c, *listofcountry)
droplist.config(width=20)
c.set('Select your Country')
droplist.place(x=236,y=210)
l=Label(top,text="Language",width=20,font=('bold',12)).place(x=75,y=270)
var1=IntVar()
Checkbutton(top,text="English", variable=var1).place(x=230,y=270)
var2=IntVar()
Checkbutton(top,text="Hindi", variable=var2).place(x=290,y=270)
l=Label(top,text="Username",width=20,font=("bold",12)).place(x=70,y=320)
e3=Entry(top,textvariable=t3).place(x=240,y=320)
l=Label(top,text="Password",width=20,font=("bold",12)).place(x=75,y=370)
e4=Entry(top,textvariable=t4).place(x=240,y=370)
def ins():
    a=str(t1.get())
    b=str(t2.get())
    c=str(t3.,get())
    d=int(t4.get())
    mycursor=mydb.cursor()
    sql="insert into register(Name,Email,Username,Password)values('%s','%s','%s','%d')"%(a,b,c,d)
    mycursor.execute(sql)
    mydb.commit()
    messagebox.showinfo("Info","Successfully inserted!!!")
btn=Button(top, text="Submit" , width=15,bg="black",fg="white",command=ins).place(x=130,y=420)
def click():
    import stuinfo
Button(top,text="Next",width=15,bg="white",fg="black",command=click).place(x=270,y=420)
top.mainloop()

