from tkinter import*
from tkinter import messagebox
import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",password="root",database="CSCtutorial")
top=Tk()
top.geometry("700x600")
top.title('Student Information Form')
l=Label(top,text="Student's Detail Form", width=20,font=("Algerian",28)).place(x=105,y=40)
t1=StringVar()
t2=StringVar()
t3=StringVar()
t4=StringVar()
t5=StringVar()
t6=StringVar()
l=Label(top,text="Student's Name", width=20,font=("bold",12)).place(x=20,y=110)
e1=Entry(top,width=35,textvariable=t1).place(x=190,y=110)
l=Label(top,text="Father's Name", width=20,font=("bold",12)).place(x=20,y=150)
e2=Entry(top,width=35,textvariable=t2).place(x=190,y=150)
l =Label(top,text="Date of Birth", width=20,font=("bold",12)).place(x=20,y=190)
e3=Entry(top,textvariable=t3).place(x=190,y=190)
l =Label(top,text="Gender", width=20,font=("bold",12)).place(x=20,y=230)
V=IntVar()
def hello():
    print (V.get())
Radiobutton(top,text="Male",variable=V,value=1,command=hello,font=("bold",12)).place(x=190,y=230)
Radiobutton(top,text="Female",variable=V,value=2,command=hello,font=("bold",12)).place(x=260,y=230)
Radiobutton(top,text="Others",variable=V,value=3,command=hello,font=("bold",12)).place(x=350,y=230)
l =Label(top,text="Address", width=20,font=("bold",12)).place(x=20,y=270)
e4=Entry(top,width=50,textvariable=t4).place(x=190,y=270)
var=IntVar()
l=Label(top,text="Country",width=20,font=("bold",12)).place(x=20,y=315)
list_of_country=['India', 'America','Srilanka','Australia','Germany','Canada','China','Bangladesh','Malaysia','Italy','Londan','Pakisthan' ]
c=StringVar()
droplist=OptionMenu(top,c, *list_of_country)
droplist.config(width=20)
c.set('Select your Country')
droplist.place(x=190,y=315)
l =Label(top,text="Mobile No.", width=20,font=("bold",12)).place(x=20,y=375)
e5=Entry(top,textvariable=t5).place(x=190,y=375)
l=Label(top,text="Mail ID", width=20,font=("bold",12)).place(x=20,y=425)
e6=Entry(top,width=35,textvariable=t6).place(x=190,y=425)
l =Label(top,text="I hereby declare that the above mentioned information are true\n and correct to the best of my knowledge",font=("Elephant",12))
l.place(x=100,y=480)
def ins():
    a=str(t1.get())
    b=str(t2.get())
    c=str(t3.et())
    d=str(t4.get())
    e=str(t5.get())
    f=str(t6.get())
    mycursor=mydb.cursor()
    sql="insert into studentinfo(studentsname,Fathersname,Dateofbirth,Address,Mobileno,Mailid)values('%s','%s','%s','%s','%s','%s')"%(a,b,c,d,e,f)
    mycursor.execute(sql)
    mydb.commit()
    messagebox.showinfo("Info","Your form has been successfully submitted!!!")
btn=Button(top, text="Submit" , width=15,bg="black",fg="white",command=ins).place(x=200,y=550)
def click():
    import stucourses
Button(top,text="Next",width=15,bg="white",fg="black",command=click).place(x=350,y=550)
top.mainloop()


